## 데이터프레임 합치기 연습

In [4]:
# 합칠 데이터 불러오기
import pandas as pd
csvPath = 'C:/Users/chunc/Desktop/취업캠프/python-20230220T004050Z-001/python/01. CCTV_in_Seoul.csv'
xlsPath = 'C:/Users/chunc/Desktop/취업캠프/python-20230220T004050Z-001/python/01. population_in_Seoul.xls'

In [9]:
df = pd.read_csv(csvPath)
df2 = pd.read_excel(xlsPath, header = 2, usecols = 'B, D, I, J, N')

In [7]:
# 데이터 확인
df

     기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [10]:
df2

     자치구           계       여자.1       계.2   65세이상고령자
0     합계  10197604.0  5055408.0  270636.0  1321458.0
1    종로구    162820.0    77978.0    9231.0    25425.0
2     중구    133240.0    62656.0    8928.0    20764.0
3    용산구    244203.0   118289.0   14747.0    36231.0
4    성동구    311244.0   153304.0    7864.0    39997.0
5    광진구    372164.0   182612.0   14953.0    42214.0
6   동대문구    369496.0   177058.0   15417.0    54173.0
7    중랑구    414503.0   205617.0    4621.0    56774.0
8    성북구    461260.0   230228.0   11487.0    64692.0
9    강북구    330192.0   166333.0    3506.0    54813.0
10   도봉구    348646.0   176340.0    2017.0    51312.0
11   노원구    569384.0   290354.0    3819.0    71941.0
12   은평구    494388.0   251606.0    4445.0    72334.0
13  서대문구    327163.0   162369.0   12181.0    48161.0
14   마포구    389649.0   197220.0   11083.0    48765.0
15   양천구    479978.0   240671.0    4029.0    52975.0
16   강서구    603772.0   305999.0    6524.0    72548.0
17   구로구    447874.0   209373.0   31387.0    56833.0
18   금천구    255082.0   116019.0   18729.0    32970.0
19  영등포구    402985.0   184367.0   34913.0    52413.0
20   동작구    412520.0   204681.0   12064.0    56013.0
21   관악구    525515.0   251113.0   18312.0    68082.0
22   서초구    450310.0   231958.0    4316.0    51733.0
23   강남구    570500.0   294824.0    4950.0    63167.0
24   송파구    667483.0   338908.0    6899.0    72506.0
25   강동구    453233.0   225531.0    4214.0    54622.0
26   NaN         NaN        NaN       NaN        NaN

In [14]:
# df2의 이름변경 해주기
df2.columns = ['구별', '서울전체', '한국인여자', '등록외국인', '고령자']
df2

      구별        서울전체      한국인여자     등록외국인        고령자
0     합계  10197604.0  5055408.0  270636.0  1321458.0
1    종로구    162820.0    77978.0    9231.0    25425.0
2     중구    133240.0    62656.0    8928.0    20764.0
3    용산구    244203.0   118289.0   14747.0    36231.0
4    성동구    311244.0   153304.0    7864.0    39997.0
5    광진구    372164.0   182612.0   14953.0    42214.0
6   동대문구    369496.0   177058.0   15417.0    54173.0
7    중랑구    414503.0   205617.0    4621.0    56774.0
8    성북구    461260.0   230228.0   11487.0    64692.0
9    강북구    330192.0   166333.0    3506.0    54813.0
10   도봉구    348646.0   176340.0    2017.0    51312.0
11   노원구    569384.0   290354.0    3819.0    71941.0
12   은평구    494388.0   251606.0    4445.0    72334.0
13  서대문구    327163.0   162369.0   12181.0    48161.0
14   마포구    389649.0   197220.0   11083.0    48765.0
15   양천구    479978.0   240671.0    4029.0    52975.0
16   강서구    603772.0   305999.0    6524.0    72548.0
17   구로구    447874.0   209373.0   31387.0    56833.0
18   금천구    255082.0   116019.0   18729.0    32970.0
19  영등포구    402985.0   184367.0   34913.0    52413.0
20   동작구    412520.0   204681.0   12064.0    56013.0
21   관악구    525515.0   251113.0   18312.0    68082.0
22   서초구    450310.0   231958.0    4316.0    51733.0
23   강남구    570500.0   294824.0    4950.0    63167.0
24   송파구    667483.0   338908.0    6899.0    72506.0
25   강동구    453233.0   225531.0    4214.0    54622.0
26   NaN         NaN        NaN       NaN        NaN

## 방법1: concat함수 사용

In [19]:
# concat함수 이용하여 데이터프레임 합치기
# axis = 0
concat_df1 = pd.concat([df, df2], sort = False, axis = 0)
concat_df1

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,NaN,NaN,NaN,NaN,NaN
1,강동구,773.0,379.0,99.0,155.0,377.0,NaN,NaN,NaN,NaN,NaN
2,강북구,748.0,369.0,120.0,138.0,204.0,NaN,NaN,NaN,NaN,NaN
3,강서구,884.0,388.0,258.0,184.0,81.0,NaN,NaN,NaN,NaN,NaN
4,관악구,1496.0,846.0,260.0,390.0,613.0,NaN,NaN,NaN,NaN,NaN
5,광진구,707.0,573.0,78.0,53.0,174.0,NaN,NaN,NaN,NaN,NaN
6,구로구,1561.0,1142.0,173.0,246.0,323.0,NaN,NaN,NaN,NaN,NaN
7,금천구,1015.0,674.0,51.0,269.0,354.0,NaN,NaN,NaN,NaN,NaN
8,노원구,1265.0,542.0,57.0,451.0,516.0,NaN,NaN,NaN,NaN,NaN
9,도봉구,485.0,238.0,159.0,42.0,386.0,NaN,NaN,NaN,NaN,NaN
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,NaN,NaN,NaN,NaN,NaN
11,동작구,1091.0,544.0,341.0,103.0,314.0,NaN,NaN,NaN,NaN,NaN
12,마포구,574.0,314.0,118.0,169.0,379.0,NaN,NaN,NaN,NaN,NaN
13,서대문구,962.0,844.0,50.0,68.0,292.0,NaN,NaN,NaN,NaN,NaN
14,서초구,1930.0,1406.0,157.0,336.0,398.0,NaN,NaN,NaN,NaN,NaN
15,성동구,1062.0,730.0,91.0,241.0,265.0,NaN,NaN,NaN,NaN,NaN
16,성북구,1464.0,1009.0,78.0,360.0,204.0,NaN,NaN,NaN,NaN,NaN
17,송파구,618.0,529.0,21.0,68.0,463.0,NaN,NaN,NaN,NaN,NaN
18,양천구,2034.0,1843.0,142.0,30.0,467.0,NaN,NaN,NaN,NaN,NaN
19,영등포구,904.0,495.0,214.0,195.0,373.0,NaN,NaN,NaN,NaN,NaN
20,용산구,1624.0,1368.0,218.0,112.0,398.0,NaN,NaN,NaN,NaN,NaN
21,은평구,1873.0,1138.0,224.0,278.0,468.0,NaN,NaN,NaN,NaN,NaN
22,종로구,1002.0,464.0,314.0,211.0,630.0,NaN,NaN,NaN,NaN,NaN
23,중구,671.0,413.0,190.0,72.0,348.0,NaN,NaN,NaN,NaN,NaN
24,중랑구,660.0,509.0,121.0,177.0,109.0,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,합계,10197604.0,5055408.0,270636.0,1321458.0
1,NaN,NaN,NaN,NaN,NaN,NaN,종로구,162820.0,77978.0,9231.0,25425.0
2,NaN,NaN,NaN,NaN,NaN,NaN,중구,133240.0,62656.0,8928.0,20764.0
3,NaN,NaN,NaN,NaN,NaN,NaN,용산구,244203.0,118289.0,14747.0,36231.0
4,NaN,NaN,NaN,NaN,NaN,NaN,성동구,311244.0,153304.0,7864.0,39997.0
5,NaN,NaN,NaN,NaN,NaN,NaN,광진구,372164.0,182612.0,14953.0,42214.0
6,NaN,NaN,NaN,NaN,NaN,NaN,동대문구,369496.0,177058.0,15417.0,54173.0
7,NaN,NaN,NaN,NaN,NaN,NaN,중랑구,414503.0,205617.0,4621.0,56774.0
8,NaN,NaN,NaN,NaN,NaN,NaN,성북구,461260.0,230228.0,11487.0,64692.0
9,NaN,NaN,NaN,NaN,NaN,NaN,강북구,330192.0,166333.0,3506.0,54813.0
10,NaN,NaN,NaN,NaN,NaN,NaN,도봉구,348646.0,176340.0,2017.0,51312.0
11,NaN,NaN,NaN,NaN,NaN,NaN,노원구,569384.0,290354.0,3819.0,71941.0
12,NaN,NaN,NaN,NaN,NaN,NaN,은평구,494388.0,251606.0,4445.0,72334.0
13,NaN,NaN,NaN,NaN,NaN,NaN,서대문구,327163.0,162369.0,12181.0,48161.0
14,NaN,NaN,NaN,NaN,NaN,NaN,마포구,389649.0,197220.0,11083.0,48765.0
15,NaN,NaN,NaN,NaN,NaN,NaN,양천구,479978.0,240671.0,4029.0,52975.0
16,NaN,NaN,NaN,NaN,NaN,NaN,강서구,603772.0,305999.0,6524.0,72548.0
17,NaN,NaN,NaN,NaN,NaN,NaN,구로구,447874.0,209373.0,31387.0,56833.0
18,NaN,NaN,NaN,NaN,NaN,NaN,금천구,255082.0,116019.0,18729.0,32970.0
19,NaN,NaN,NaN,NaN,NaN,NaN,영등포구,402985.0,184367.0,34913.0,52413.0
20,NaN,NaN,NaN,NaN,NaN,NaN,동작구,412520.0,204681.0,12064.0,56013.0
21,NaN,NaN,NaN,NaN,NaN,NaN,관악구,525515.0,251113.0,18312.0,68082.0
22,NaN,NaN,NaN,NaN,NaN,NaN,서초구,450310.0,231958.0,4316.0,51733.0
23,NaN,NaN,NaN,NaN,NaN,NaN,강남구,570500.0,294824.0,4950.0,63167.0
24,NaN,NaN,NaN,NaN,NaN,NaN,송파구,667483.0,338908.0,6899.0,72506.0
25,NaN,NaN,NaN,NaN,NaN,NaN,강동구,453233.0,225531.0,4214.0,54622.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# axis = 1
concat_df2 = pd.concat([df, df2], sort = False, axis = 1)
concat_df2

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,합계,10197604.0,5055408.0,270636.0,1321458.0
1,강동구,773.0,379.0,99.0,155.0,377.0,종로구,162820.0,77978.0,9231.0,25425.0
2,강북구,748.0,369.0,120.0,138.0,204.0,중구,133240.0,62656.0,8928.0,20764.0
3,강서구,884.0,388.0,258.0,184.0,81.0,용산구,244203.0,118289.0,14747.0,36231.0
4,관악구,1496.0,846.0,260.0,390.0,613.0,성동구,311244.0,153304.0,7864.0,39997.0
5,광진구,707.0,573.0,78.0,53.0,174.0,광진구,372164.0,182612.0,14953.0,42214.0
6,구로구,1561.0,1142.0,173.0,246.0,323.0,동대문구,369496.0,177058.0,15417.0,54173.0
7,금천구,1015.0,674.0,51.0,269.0,354.0,중랑구,414503.0,205617.0,4621.0,56774.0
8,노원구,1265.0,542.0,57.0,451.0,516.0,성북구,461260.0,230228.0,11487.0,64692.0
9,도봉구,485.0,238.0,159.0,42.0,386.0,강북구,330192.0,166333.0,3506.0,54813.0
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,도봉구,348646.0,176340.0,2017.0,51312.0
11,동작구,1091.0,544.0,341.0,103.0,314.0,노원구,569384.0,290354.0,3819.0,71941.0
12,마포구,574.0,314.0,118.0,169.0,379.0,은평구,494388.0,251606.0,4445.0,72334.0
13,서대문구,962.0,844.0,50.0,68.0,292.0,서대문구,327163.0,162369.0,12181.0,48161.0
14,서초구,1930.0,1406.0,157.0,336.0,398.0,마포구,389649.0,197220.0,11083.0,48765.0
15,성동구,1062.0,730.0,91.0,241.0,265.0,양천구,479978.0,240671.0,4029.0,52975.0
16,성북구,1464.0,1009.0,78.0,360.0,204.0,강서구,603772.0,305999.0,6524.0,72548.0
17,송파구,618.0,529.0,21.0,68.0,463.0,구로구,447874.0,209373.0,31387.0,56833.0
18,양천구,2034.0,1843.0,142.0,30.0,467.0,금천구,255082.0,116019.0,18729.0,32970.0
19,영등포구,904.0,495.0,214.0,195.0,373.0,영등포구,402985.0,184367.0,34913.0,52413.0
20,용산구,1624.0,1368.0,218.0,112.0,398.0,동작구,412520.0,204681.0,12064.0,56013.0
21,은평구,1873.0,1138.0,224.0,278.0,468.0,관악구,525515.0,251113.0,18312.0,68082.0
22,종로구,1002.0,464.0,314.0,211.0,630.0,서초구,450310.0,231958.0,4316.0,51733.0
23,중구,671.0,413.0,190.0,72.0,348.0,강남구,570500.0,294824.0,4950.0,63167.0
24,중랑구,660.0,509.0,121.0,177.0,109.0,송파구,667483.0,338908.0,6899.0,72506.0
25,NaN,NaN,NaN,NaN,NaN,NaN,강동구,453233.0,225531.0,4214.0,54622.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# 인덱스 번호 초기화
concat_df1.reset_index(drop = True)

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,NaN,NaN,NaN,NaN,NaN
1,강동구,773.0,379.0,99.0,155.0,377.0,NaN,NaN,NaN,NaN,NaN
2,강북구,748.0,369.0,120.0,138.0,204.0,NaN,NaN,NaN,NaN,NaN
3,강서구,884.0,388.0,258.0,184.0,81.0,NaN,NaN,NaN,NaN,NaN
4,관악구,1496.0,846.0,260.0,390.0,613.0,NaN,NaN,NaN,NaN,NaN
5,광진구,707.0,573.0,78.0,53.0,174.0,NaN,NaN,NaN,NaN,NaN
6,구로구,1561.0,1142.0,173.0,246.0,323.0,NaN,NaN,NaN,NaN,NaN
7,금천구,1015.0,674.0,51.0,269.0,354.0,NaN,NaN,NaN,NaN,NaN
8,노원구,1265.0,542.0,57.0,451.0,516.0,NaN,NaN,NaN,NaN,NaN
9,도봉구,485.0,238.0,159.0,42.0,386.0,NaN,NaN,NaN,NaN,NaN
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,NaN,NaN,NaN,NaN,NaN
11,동작구,1091.0,544.0,341.0,103.0,314.0,NaN,NaN,NaN,NaN,NaN
12,마포구,574.0,314.0,118.0,169.0,379.0,NaN,NaN,NaN,NaN,NaN
13,서대문구,962.0,844.0,50.0,68.0,292.0,NaN,NaN,NaN,NaN,NaN
14,서초구,1930.0,1406.0,157.0,336.0,398.0,NaN,NaN,NaN,NaN,NaN
15,성동구,1062.0,730.0,91.0,241.0,265.0,NaN,NaN,NaN,NaN,NaN
16,성북구,1464.0,1009.0,78.0,360.0,204.0,NaN,NaN,NaN,NaN,NaN
17,송파구,618.0,529.0,21.0,68.0,463.0,NaN,NaN,NaN,NaN,NaN
18,양천구,2034.0,1843.0,142.0,30.0,467.0,NaN,NaN,NaN,NaN,NaN
19,영등포구,904.0,495.0,214.0,195.0,373.0,NaN,NaN,NaN,NaN,NaN
20,용산구,1624.0,1368.0,218.0,112.0,398.0,NaN,NaN,NaN,NaN,NaN
21,은평구,1873.0,1138.0,224.0,278.0,468.0,NaN,NaN,NaN,NaN,NaN
22,종로구,1002.0,464.0,314.0,211.0,630.0,NaN,NaN,NaN,NaN,NaN
23,중구,671.0,413.0,190.0,72.0,348.0,NaN,NaN,NaN,NaN,NaN
24,중랑구,660.0,509.0,121.0,177.0,109.0,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,합계,10197604.0,5055408.0,270636.0,1321458.0
26,NaN,NaN,NaN,NaN,NaN,NaN,종로구,162820.0,77978.0,9231.0,25425.0
27,NaN,NaN,NaN,NaN,NaN,NaN,중구,133240.0,62656.0,8928.0,20764.0
28,NaN,NaN,NaN,NaN,NaN,NaN,용산구,244203.0,118289.0,14747.0,36231.0
29,NaN,NaN,NaN,NaN,NaN,NaN,성동구,311244.0,153304.0,7864.0,39997.0
30,NaN,NaN,NaN,NaN,NaN,NaN,광진구,372164.0,182612.0,14953.0,42214.0
31,NaN,NaN,NaN,NaN,NaN,NaN,동대문구,369496.0,177058.0,15417.0,54173.0
32,NaN,NaN,NaN,NaN,NaN,NaN,중랑구,414503.0,205617.0,4621.0,56774.0
33,NaN,NaN,NaN,NaN,NaN,NaN,성북구,461260.0,230228.0,11487.0,64692.0
34,NaN,NaN,NaN,NaN,NaN,NaN,강북구,330192.0,166333.0,3506.0,54813.0
35,NaN,NaN,NaN,NaN,NaN,NaN,도봉구,348646.0,176340.0,2017.0,51312.0
36,NaN,NaN,NaN,NaN,NaN,NaN,노원구,569384.0,290354.0,3819.0,71941.0
37,NaN,NaN,NaN,NaN,NaN,NaN,은평구,494388.0,251606.0,4445.0,72334.0
38,NaN,NaN,NaN,NaN,NaN,NaN,서대문구,327163.0,162369.0,12181.0,48161.0
39,NaN,NaN,NaN,NaN,NaN,NaN,마포구,389649.0,197220.0,11083.0,48765.0
40,NaN,NaN,NaN,NaN,NaN,NaN,양천구,479978.0,240671.0,4029.0,52975.0
41,NaN,NaN,NaN,NaN,NaN,NaN,강서구,603772.0,305999.0,6524.0,72548.0
42,NaN,NaN,NaN,NaN,NaN,NaN,구로구,447874.0,209373.0,31387.0,56833.0
43,NaN,NaN,NaN,NaN,NaN,NaN,금천구,255082.0,116019.0,18729.0,32970.0
44,NaN,NaN,NaN,NaN,NaN,NaN,영등포구,402985.0,184367.0,34913.0,52413.0
45,NaN,NaN,NaN,NaN,NaN,NaN,동작구,412520.0,204681.0,12064.0,56013.0
46,NaN,NaN,NaN,NaN,NaN,NaN,관악구,525515.0,251113.0,18312.0,68082.0
47,NaN,NaN,NaN,NaN,NaN,NaN,서초구,450310.0,231958.0,4316.0,51733.0
48,NaN,NaN,NaN,NaN,NaN,NaN,강남구,570500.0,294824.0,4950.0,63167.0
49,NaN,NaN,NaN,NaN,NaN,NaN,송파구,667483.0,338908.0,6899.0,72506.0
50,NaN,NaN,NaN,NaN,NaN,NaN,강동구,453233.0,225531.0,4214.0,54622.0
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
concat_df2.reset_index(drop = True)

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,합계,10197604.0,5055408.0,270636.0,1321458.0
1,강동구,773.0,379.0,99.0,155.0,377.0,종로구,162820.0,77978.0,9231.0,25425.0
2,강북구,748.0,369.0,120.0,138.0,204.0,중구,133240.0,62656.0,8928.0,20764.0
3,강서구,884.0,388.0,258.0,184.0,81.0,용산구,244203.0,118289.0,14747.0,36231.0
4,관악구,1496.0,846.0,260.0,390.0,613.0,성동구,311244.0,153304.0,7864.0,39997.0
5,광진구,707.0,573.0,78.0,53.0,174.0,광진구,372164.0,182612.0,14953.0,42214.0
6,구로구,1561.0,1142.0,173.0,246.0,323.0,동대문구,369496.0,177058.0,15417.0,54173.0
7,금천구,1015.0,674.0,51.0,269.0,354.0,중랑구,414503.0,205617.0,4621.0,56774.0
8,노원구,1265.0,542.0,57.0,451.0,516.0,성북구,461260.0,230228.0,11487.0,64692.0
9,도봉구,485.0,238.0,159.0,42.0,386.0,강북구,330192.0,166333.0,3506.0,54813.0
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,도봉구,348646.0,176340.0,2017.0,51312.0
11,동작구,1091.0,544.0,341.0,103.0,314.0,노원구,569384.0,290354.0,3819.0,71941.0
12,마포구,574.0,314.0,118.0,169.0,379.0,은평구,494388.0,251606.0,4445.0,72334.0
13,서대문구,962.0,844.0,50.0,68.0,292.0,서대문구,327163.0,162369.0,12181.0,48161.0
14,서초구,1930.0,1406.0,157.0,336.0,398.0,마포구,389649.0,197220.0,11083.0,48765.0
15,성동구,1062.0,730.0,91.0,241.0,265.0,양천구,479978.0,240671.0,4029.0,52975.0
16,성북구,1464.0,1009.0,78.0,360.0,204.0,강서구,603772.0,305999.0,6524.0,72548.0
17,송파구,618.0,529.0,21.0,68.0,463.0,구로구,447874.0,209373.0,31387.0,56833.0
18,양천구,2034.0,1843.0,142.0,30.0,467.0,금천구,255082.0,116019.0,18729.0,32970.0
19,영등포구,904.0,495.0,214.0,195.0,373.0,영등포구,402985.0,184367.0,34913.0,52413.0
20,용산구,1624.0,1368.0,218.0,112.0,398.0,동작구,412520.0,204681.0,12064.0,56013.0
21,은평구,1873.0,1138.0,224.0,278.0,468.0,관악구,525515.0,251113.0,18312.0,68082.0
22,종로구,1002.0,464.0,314.0,211.0,630.0,서초구,450310.0,231958.0,4316.0,51733.0
23,중구,671.0,413.0,190.0,72.0,348.0,강남구,570500.0,294824.0,4950.0,63167.0
24,중랑구,660.0,509.0,121.0,177.0,109.0,송파구,667483.0,338908.0,6899.0,72506.0
25,NaN,NaN,NaN,NaN,NaN,NaN,강동구,453233.0,225531.0,4214.0,54622.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# 컬럼명이 중복일때 바꿔주는 방법
# 방법1: 합친 후 컬럼명을 바꿔주어 컬럼을 삭제해준다
# 방법2: 합치기 전 이름을 달리하여 저장한 후 컬럼을 삭제해준다
concat_df1.drop('구별', axis = 1)

,기관명,소계,2013년도 이전,2014년,2015년,2016년,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,NaN,NaN,NaN,NaN
1,강동구,773.0,379.0,99.0,155.0,377.0,NaN,NaN,NaN,NaN
2,강북구,748.0,369.0,120.0,138.0,204.0,NaN,NaN,NaN,NaN
3,강서구,884.0,388.0,258.0,184.0,81.0,NaN,NaN,NaN,NaN
4,관악구,1496.0,846.0,260.0,390.0,613.0,NaN,NaN,NaN,NaN
5,광진구,707.0,573.0,78.0,53.0,174.0,NaN,NaN,NaN,NaN
6,구로구,1561.0,1142.0,173.0,246.0,323.0,NaN,NaN,NaN,NaN
7,금천구,1015.0,674.0,51.0,269.0,354.0,NaN,NaN,NaN,NaN
8,노원구,1265.0,542.0,57.0,451.0,516.0,NaN,NaN,NaN,NaN
9,도봉구,485.0,238.0,159.0,42.0,386.0,NaN,NaN,NaN,NaN
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,NaN,NaN,NaN,NaN
11,동작구,1091.0,544.0,341.0,103.0,314.0,NaN,NaN,NaN,NaN
12,마포구,574.0,314.0,118.0,169.0,379.0,NaN,NaN,NaN,NaN
13,서대문구,962.0,844.0,50.0,68.0,292.0,NaN,NaN,NaN,NaN
14,서초구,1930.0,1406.0,157.0,336.0,398.0,NaN,NaN,NaN,NaN
15,성동구,1062.0,730.0,91.0,241.0,265.0,NaN,NaN,NaN,NaN
16,성북구,1464.0,1009.0,78.0,360.0,204.0,NaN,NaN,NaN,NaN
17,송파구,618.0,529.0,21.0,68.0,463.0,NaN,NaN,NaN,NaN
18,양천구,2034.0,1843.0,142.0,30.0,467.0,NaN,NaN,NaN,NaN
19,영등포구,904.0,495.0,214.0,195.0,373.0,NaN,NaN,NaN,NaN
20,용산구,1624.0,1368.0,218.0,112.0,398.0,NaN,NaN,NaN,NaN
21,은평구,1873.0,1138.0,224.0,278.0,468.0,NaN,NaN,NaN,NaN
22,종로구,1002.0,464.0,314.0,211.0,630.0,NaN,NaN,NaN,NaN
23,중구,671.0,413.0,190.0,72.0,348.0,NaN,NaN,NaN,NaN
24,중랑구,660.0,509.0,121.0,177.0,109.0,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,10197604.0,5055408.0,270636.0,1321458.0
1,NaN,NaN,NaN,NaN,NaN,NaN,162820.0,77978.0,9231.0,25425.0
2,NaN,NaN,NaN,NaN,NaN,NaN,133240.0,62656.0,8928.0,20764.0
3,NaN,NaN,NaN,NaN,NaN,NaN,244203.0,118289.0,14747.0,36231.0
4,NaN,NaN,NaN,NaN,NaN,NaN,311244.0,153304.0,7864.0,39997.0
5,NaN,NaN,NaN,NaN,NaN,NaN,372164.0,182612.0,14953.0,42214.0
6,NaN,NaN,NaN,NaN,NaN,NaN,369496.0,177058.0,15417.0,54173.0
7,NaN,NaN,NaN,NaN,NaN,NaN,414503.0,205617.0,4621.0,56774.0
8,NaN,NaN,NaN,NaN,NaN,NaN,461260.0,230228.0,11487.0,64692.0
9,NaN,NaN,NaN,NaN,NaN,NaN,330192.0,166333.0,3506.0,54813.0
10,NaN,NaN,NaN,NaN,NaN,NaN,348646.0,176340.0,2017.0,51312.0
11,NaN,NaN,NaN,NaN,NaN,NaN,569384.0,290354.0,3819.0,71941.0
12,NaN,NaN,NaN,NaN,NaN,NaN,494388.0,251606.0,4445.0,72334.0
13,NaN,NaN,NaN,NaN,NaN,NaN,327163.0,162369.0,12181.0,48161.0
14,NaN,NaN,NaN,NaN,NaN,NaN,389649.0,197220.0,11083.0,48765.0
15,NaN,NaN,NaN,NaN,NaN,NaN,479978.0,240671.0,4029.0,52975.0
16,NaN,NaN,NaN,NaN,NaN,NaN,603772.0,305999.0,6524.0,72548.0
17,NaN,NaN,NaN,NaN,NaN,NaN,447874.0,209373.0,31387.0,56833.0
18,NaN,NaN,NaN,NaN,NaN,NaN,255082.0,116019.0,18729.0,32970.0
19,NaN,NaN,NaN,NaN,NaN,NaN,402985.0,184367.0,34913.0,52413.0
20,NaN,NaN,NaN,NaN,NaN,NaN,412520.0,204681.0,12064.0,56013.0
21,NaN,NaN,NaN,NaN,NaN,NaN,525515.0,251113.0,18312.0,68082.0
22,NaN,NaN,NaN,NaN,NaN,NaN,450310.0,231958.0,4316.0,51733.0
23,NaN,NaN,NaN,NaN,NaN,NaN,570500.0,294824.0,4950.0,63167.0
24,NaN,NaN,NaN,NaN,NaN,NaN,667483.0,338908.0,6899.0,72506.0
25,NaN,NaN,NaN,NaN,NaN,NaN,453233.0,225531.0,4214.0,54622.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
concat_df2.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년', '구별', '서울전체',
       '한국인여자', '등록외국인', '고령자'],
      dtype='object')

In [29]:
concat_df2.drop('구별', axis = 1)

,기관명,소계,2013년도 이전,2014년,2015년,2016년,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,10197604.0,5055408.0,270636.0,1321458.0
1,강동구,773.0,379.0,99.0,155.0,377.0,162820.0,77978.0,9231.0,25425.0
2,강북구,748.0,369.0,120.0,138.0,204.0,133240.0,62656.0,8928.0,20764.0
3,강서구,884.0,388.0,258.0,184.0,81.0,244203.0,118289.0,14747.0,36231.0
4,관악구,1496.0,846.0,260.0,390.0,613.0,311244.0,153304.0,7864.0,39997.0
5,광진구,707.0,573.0,78.0,53.0,174.0,372164.0,182612.0,14953.0,42214.0
6,구로구,1561.0,1142.0,173.0,246.0,323.0,369496.0,177058.0,15417.0,54173.0
7,금천구,1015.0,674.0,51.0,269.0,354.0,414503.0,205617.0,4621.0,56774.0
8,노원구,1265.0,542.0,57.0,451.0,516.0,461260.0,230228.0,11487.0,64692.0
9,도봉구,485.0,238.0,159.0,42.0,386.0,330192.0,166333.0,3506.0,54813.0
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,348646.0,176340.0,2017.0,51312.0
11,동작구,1091.0,544.0,341.0,103.0,314.0,569384.0,290354.0,3819.0,71941.0
12,마포구,574.0,314.0,118.0,169.0,379.0,494388.0,251606.0,4445.0,72334.0
13,서대문구,962.0,844.0,50.0,68.0,292.0,327163.0,162369.0,12181.0,48161.0
14,서초구,1930.0,1406.0,157.0,336.0,398.0,389649.0,197220.0,11083.0,48765.0
15,성동구,1062.0,730.0,91.0,241.0,265.0,479978.0,240671.0,4029.0,52975.0
16,성북구,1464.0,1009.0,78.0,360.0,204.0,603772.0,305999.0,6524.0,72548.0
17,송파구,618.0,529.0,21.0,68.0,463.0,447874.0,209373.0,31387.0,56833.0
18,양천구,2034.0,1843.0,142.0,30.0,467.0,255082.0,116019.0,18729.0,32970.0
19,영등포구,904.0,495.0,214.0,195.0,373.0,402985.0,184367.0,34913.0,52413.0
20,용산구,1624.0,1368.0,218.0,112.0,398.0,412520.0,204681.0,12064.0,56013.0
21,은평구,1873.0,1138.0,224.0,278.0,468.0,525515.0,251113.0,18312.0,68082.0
22,종로구,1002.0,464.0,314.0,211.0,630.0,450310.0,231958.0,4316.0,51733.0
23,중구,671.0,413.0,190.0,72.0,348.0,570500.0,294824.0,4950.0,63167.0
24,중랑구,660.0,509.0,121.0,177.0,109.0,667483.0,338908.0,6899.0,72506.0
25,NaN,NaN,NaN,NaN,NaN,NaN,453233.0,225531.0,4214.0,54622.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 방법2: merge함수 이용하기

In [30]:
df = pd.read_csv(csvPath)
df2 = pd.read_excel(xlsPath, header = 2, usecols = 'B, D, I, J, N')

In [34]:
df2.columns = ['구별', '서울전체', '한국인여자', '등록외국인', '고령자']
df2

      구별        서울전체      한국인여자     등록외국인        고령자
0     합계  10197604.0  5055408.0  270636.0  1321458.0
1    종로구    162820.0    77978.0    9231.0    25425.0
2     중구    133240.0    62656.0    8928.0    20764.0
3    용산구    244203.0   118289.0   14747.0    36231.0
4    성동구    311244.0   153304.0    7864.0    39997.0
5    광진구    372164.0   182612.0   14953.0    42214.0
6   동대문구    369496.0   177058.0   15417.0    54173.0
7    중랑구    414503.0   205617.0    4621.0    56774.0
8    성북구    461260.0   230228.0   11487.0    64692.0
9    강북구    330192.0   166333.0    3506.0    54813.0
10   도봉구    348646.0   176340.0    2017.0    51312.0
11   노원구    569384.0   290354.0    3819.0    71941.0
12   은평구    494388.0   251606.0    4445.0    72334.0
13  서대문구    327163.0   162369.0   12181.0    48161.0
14   마포구    389649.0   197220.0   11083.0    48765.0
15   양천구    479978.0   240671.0    4029.0    52975.0
16   강서구    603772.0   305999.0    6524.0    72548.0
17   구로구    447874.0   209373.0   31387.0    56833.0
18   금천구    255082.0   116019.0   18729.0    32970.0
19  영등포구    402985.0   184367.0   34913.0    52413.0
20   동작구    412520.0   204681.0   12064.0    56013.0
21   관악구    525515.0   251113.0   18312.0    68082.0
22   서초구    450310.0   231958.0    4316.0    51733.0
23   강남구    570500.0   294824.0    4950.0    63167.0
24   송파구    667483.0   338908.0    6899.0    72506.0
25   강동구    453233.0   225531.0    4214.0    54622.0
26   NaN         NaN        NaN       NaN        NaN

In [42]:
# merge함수: inner조인
merge_df = pd.merge(df, df2, left_on = '기관명', right_on = '구별', how = 'inner')
merge_df

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780,1292,430,584,932,강남구,570500.0,294824.0,4950.0,63167.0
1,강동구,773,379,99,155,377,강동구,453233.0,225531.0,4214.0,54622.0
2,강북구,748,369,120,138,204,강북구,330192.0,166333.0,3506.0,54813.0
3,강서구,884,388,258,184,81,강서구,603772.0,305999.0,6524.0,72548.0
4,관악구,1496,846,260,390,613,관악구,525515.0,251113.0,18312.0,68082.0
5,광진구,707,573,78,53,174,광진구,372164.0,182612.0,14953.0,42214.0
6,구로구,1561,1142,173,246,323,구로구,447874.0,209373.0,31387.0,56833.0
7,금천구,1015,674,51,269,354,금천구,255082.0,116019.0,18729.0,32970.0
8,노원구,1265,542,57,451,516,노원구,569384.0,290354.0,3819.0,71941.0
9,도봉구,485,238,159,42,386,도봉구,348646.0,176340.0,2017.0,51312.0
10,동대문구,1294,1070,23,198,579,동대문구,369496.0,177058.0,15417.0,54173.0
11,동작구,1091,544,341,103,314,동작구,412520.0,204681.0,12064.0,56013.0
12,마포구,574,314,118,169,379,마포구,389649.0,197220.0,11083.0,48765.0
13,서대문구,962,844,50,68,292,서대문구,327163.0,162369.0,12181.0,48161.0
14,서초구,1930,1406,157,336,398,서초구,450310.0,231958.0,4316.0,51733.0
15,성동구,1062,730,91,241,265,성동구,311244.0,153304.0,7864.0,39997.0
16,성북구,1464,1009,78,360,204,성북구,461260.0,230228.0,11487.0,64692.0
17,송파구,618,529,21,68,463,송파구,667483.0,338908.0,6899.0,72506.0
18,양천구,2034,1843,142,30,467,양천구,479978.0,240671.0,4029.0,52975.0
19,영등포구,904,495,214,195,373,영등포구,402985.0,184367.0,34913.0,52413.0
20,용산구,1624,1368,218,112,398,용산구,244203.0,118289.0,14747.0,36231.0
21,은평구,1873,1138,224,278,468,은평구,494388.0,251606.0,4445.0,72334.0
22,종로구,1002,464,314,211,630,종로구,162820.0,77978.0,9231.0,25425.0
23,중구,671,413,190,72,348,중구,133240.0,62656.0,8928.0,20764.0
24,중랑구,660,509,121,177,109,중랑구,414503.0,205617.0,4621.0,56774.0

In [44]:
# 중복컬럼 삭제
merge_df.drop('구별', axis = 1, inplace = True)

In [45]:
merge_df

,기관명,소계,2013년도 이전,2014년,2015년,2016년,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780,1292,430,584,932,570500.0,294824.0,4950.0,63167.0
1,강동구,773,379,99,155,377,453233.0,225531.0,4214.0,54622.0
2,강북구,748,369,120,138,204,330192.0,166333.0,3506.0,54813.0
3,강서구,884,388,258,184,81,603772.0,305999.0,6524.0,72548.0
4,관악구,1496,846,260,390,613,525515.0,251113.0,18312.0,68082.0
5,광진구,707,573,78,53,174,372164.0,182612.0,14953.0,42214.0
6,구로구,1561,1142,173,246,323,447874.0,209373.0,31387.0,56833.0
7,금천구,1015,674,51,269,354,255082.0,116019.0,18729.0,32970.0
8,노원구,1265,542,57,451,516,569384.0,290354.0,3819.0,71941.0
9,도봉구,485,238,159,42,386,348646.0,176340.0,2017.0,51312.0
10,동대문구,1294,1070,23,198,579,369496.0,177058.0,15417.0,54173.0
11,동작구,1091,544,341,103,314,412520.0,204681.0,12064.0,56013.0
12,마포구,574,314,118,169,379,389649.0,197220.0,11083.0,48765.0
13,서대문구,962,844,50,68,292,327163.0,162369.0,12181.0,48161.0
14,서초구,1930,1406,157,336,398,450310.0,231958.0,4316.0,51733.0
15,성동구,1062,730,91,241,265,311244.0,153304.0,7864.0,39997.0
16,성북구,1464,1009,78,360,204,461260.0,230228.0,11487.0,64692.0
17,송파구,618,529,21,68,463,667483.0,338908.0,6899.0,72506.0
18,양천구,2034,1843,142,30,467,479978.0,240671.0,4029.0,52975.0
19,영등포구,904,495,214,195,373,402985.0,184367.0,34913.0,52413.0
20,용산구,1624,1368,218,112,398,244203.0,118289.0,14747.0,36231.0
21,은평구,1873,1138,224,278,468,494388.0,251606.0,4445.0,72334.0
22,종로구,1002,464,314,211,630,162820.0,77978.0,9231.0,25425.0
23,중구,671,413,190,72,348,133240.0,62656.0,8928.0,20764.0
24,중랑구,660,509,121,177,109,414503.0,205617.0,4621.0,56774.0

In [46]:
# merge함수: outer조인
merge_df2 = pd.merge(df, df2, left_on = '기관명', right_on = '구별', how = 'outer')
merge_df2

,기관명,소계,2013년도 이전,2014년,2015년,2016년,구별,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,강남구,570500.0,294824.0,4950.0,63167.0
1,강동구,773.0,379.0,99.0,155.0,377.0,강동구,453233.0,225531.0,4214.0,54622.0
2,강북구,748.0,369.0,120.0,138.0,204.0,강북구,330192.0,166333.0,3506.0,54813.0
3,강서구,884.0,388.0,258.0,184.0,81.0,강서구,603772.0,305999.0,6524.0,72548.0
4,관악구,1496.0,846.0,260.0,390.0,613.0,관악구,525515.0,251113.0,18312.0,68082.0
5,광진구,707.0,573.0,78.0,53.0,174.0,광진구,372164.0,182612.0,14953.0,42214.0
6,구로구,1561.0,1142.0,173.0,246.0,323.0,구로구,447874.0,209373.0,31387.0,56833.0
7,금천구,1015.0,674.0,51.0,269.0,354.0,금천구,255082.0,116019.0,18729.0,32970.0
8,노원구,1265.0,542.0,57.0,451.0,516.0,노원구,569384.0,290354.0,3819.0,71941.0
9,도봉구,485.0,238.0,159.0,42.0,386.0,도봉구,348646.0,176340.0,2017.0,51312.0
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,동대문구,369496.0,177058.0,15417.0,54173.0
11,동작구,1091.0,544.0,341.0,103.0,314.0,동작구,412520.0,204681.0,12064.0,56013.0
12,마포구,574.0,314.0,118.0,169.0,379.0,마포구,389649.0,197220.0,11083.0,48765.0
13,서대문구,962.0,844.0,50.0,68.0,292.0,서대문구,327163.0,162369.0,12181.0,48161.0
14,서초구,1930.0,1406.0,157.0,336.0,398.0,서초구,450310.0,231958.0,4316.0,51733.0
15,성동구,1062.0,730.0,91.0,241.0,265.0,성동구,311244.0,153304.0,7864.0,39997.0
16,성북구,1464.0,1009.0,78.0,360.0,204.0,성북구,461260.0,230228.0,11487.0,64692.0
17,송파구,618.0,529.0,21.0,68.0,463.0,송파구,667483.0,338908.0,6899.0,72506.0
18,양천구,2034.0,1843.0,142.0,30.0,467.0,양천구,479978.0,240671.0,4029.0,52975.0
19,영등포구,904.0,495.0,214.0,195.0,373.0,영등포구,402985.0,184367.0,34913.0,52413.0
20,용산구,1624.0,1368.0,218.0,112.0,398.0,용산구,244203.0,118289.0,14747.0,36231.0
21,은평구,1873.0,1138.0,224.0,278.0,468.0,은평구,494388.0,251606.0,4445.0,72334.0
22,종로구,1002.0,464.0,314.0,211.0,630.0,종로구,162820.0,77978.0,9231.0,25425.0
23,중구,671.0,413.0,190.0,72.0,348.0,중구,133240.0,62656.0,8928.0,20764.0
24,중랑구,660.0,509.0,121.0,177.0,109.0,중랑구,414503.0,205617.0,4621.0,56774.0
25,NaN,NaN,NaN,NaN,NaN,NaN,합계,10197604.0,5055408.0,270636.0,1321458.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
# 중복칼럼 제거
merge_df2.drop('구별', axis = 1, inplace =True)

In [49]:
merge_df2

,기관명,소계,2013년도 이전,2014년,2015년,2016년,서울전체,한국인여자,등록외국인,고령자
0,강남구,2780.0,1292.0,430.0,584.0,932.0,570500.0,294824.0,4950.0,63167.0
1,강동구,773.0,379.0,99.0,155.0,377.0,453233.0,225531.0,4214.0,54622.0
2,강북구,748.0,369.0,120.0,138.0,204.0,330192.0,166333.0,3506.0,54813.0
3,강서구,884.0,388.0,258.0,184.0,81.0,603772.0,305999.0,6524.0,72548.0
4,관악구,1496.0,846.0,260.0,390.0,613.0,525515.0,251113.0,18312.0,68082.0
5,광진구,707.0,573.0,78.0,53.0,174.0,372164.0,182612.0,14953.0,42214.0
6,구로구,1561.0,1142.0,173.0,246.0,323.0,447874.0,209373.0,31387.0,56833.0
7,금천구,1015.0,674.0,51.0,269.0,354.0,255082.0,116019.0,18729.0,32970.0
8,노원구,1265.0,542.0,57.0,451.0,516.0,569384.0,290354.0,3819.0,71941.0
9,도봉구,485.0,238.0,159.0,42.0,386.0,348646.0,176340.0,2017.0,51312.0
10,동대문구,1294.0,1070.0,23.0,198.0,579.0,369496.0,177058.0,15417.0,54173.0
11,동작구,1091.0,544.0,341.0,103.0,314.0,412520.0,204681.0,12064.0,56013.0
12,마포구,574.0,314.0,118.0,169.0,379.0,389649.0,197220.0,11083.0,48765.0
13,서대문구,962.0,844.0,50.0,68.0,292.0,327163.0,162369.0,12181.0,48161.0
14,서초구,1930.0,1406.0,157.0,336.0,398.0,450310.0,231958.0,4316.0,51733.0
15,성동구,1062.0,730.0,91.0,241.0,265.0,311244.0,153304.0,7864.0,39997.0
16,성북구,1464.0,1009.0,78.0,360.0,204.0,461260.0,230228.0,11487.0,64692.0
17,송파구,618.0,529.0,21.0,68.0,463.0,667483.0,338908.0,6899.0,72506.0
18,양천구,2034.0,1843.0,142.0,30.0,467.0,479978.0,240671.0,4029.0,52975.0
19,영등포구,904.0,495.0,214.0,195.0,373.0,402985.0,184367.0,34913.0,52413.0
20,용산구,1624.0,1368.0,218.0,112.0,398.0,244203.0,118289.0,14747.0,36231.0
21,은평구,1873.0,1138.0,224.0,278.0,468.0,494388.0,251606.0,4445.0,72334.0
22,종로구,1002.0,464.0,314.0,211.0,630.0,162820.0,77978.0,9231.0,25425.0
23,중구,671.0,413.0,190.0,72.0,348.0,133240.0,62656.0,8928.0,20764.0
24,중랑구,660.0,509.0,121.0,177.0,109.0,414503.0,205617.0,4621.0,56774.0
25,NaN,NaN,NaN,NaN,NaN,NaN,10197604.0,5055408.0,270636.0,1321458.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN